###
# This workflow represents a possibly auto triggered deploy, and a manually triggered deploy
# It will look at a release based tag, and a manually entered version for deployment
###

name: Multi-triggered Deploy
on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to be deployed"
        required: true
  create:
    types: [tag]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Temp echo the event
        run: |
          echo ${{ github.event }}

      - name: Map Manual Variables to Environment
        if: ${{  github.event.inputs.version }}
        run: |
          echo "DEPLOY_VERSION=${{ github.event.inputs.version }}" >> ${GITHUB_ENV}

      - name: Map Release Variables to Environment
        if: ${{ github.event.ref }}
        run: |
          echo "DEPLOY_VERSION=${{ github.event.ref }}" >> ${GITHUB_ENV}

      - name: Echo the results
        run: |
          echo ${{ env.DEPLOY_VERSION }}
