# NPM Publish
# This action will on commit to master, publish the latest version to github packages
# It leverages the latest commit tag to determine the version to publish.
name: NPM Publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: ${{ secrets.GITHUB_COMMIT_TOKEN }}

      - name: yarn-cache
        uses: actions/cache@v1
        id: yarn-cache
        env:
          cache-name: npm-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}

      - uses: actions/setup-node@v1
        with:
          node-version: 10.18.0
          registry-url: "https://npm.pkg.github.com"

      - name: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn install

      - name: yarn build # pretend we're doing an NPM publish
        run: |
          yarn run build

      - name: Get Next Version
        id: get_next_version
        run: |
          run: yarn ts-node src/actions/get-next-version.ts
        env:
          TOKEN: ${{ secrets.GITHUB_COMMIT_TOKEN }}
          VERSION_CHANGE: "PATCH"

      - name: Publish the changes
        id: get-next-version
        run: |
          run: yarn ts-node src/actions/package-version-bump.ts
        env:
          TOKEN: ${{ secrets.GITHUB_COMMIT_TOKEN }}
          NEXT_VERSION: ${{steps.get_next_version.outputs.next_version}}
          CREATE_GIT_COMMIT: true
